publish_interval: 100
texts:
  - /point_cloud_tf/idx_start
  - /point_cloud_tf/window_size
  - /point_cloud_tf/x
  - /point_cloud_tf/y
  - /point_cloud_tf/z
  - /point_cloud_tf/roll
  - /point_cloud_tf/pitch
  - /point_cloud_tf/yaw
settings:
  - /point_cloud_tf/idx_start:
      min: 0
      max: 1000000
      is_repeat: false
  - /point_cloud_tf/window_size:
      min: 10
      max: 300
      is_repeat: false
  - /point_cloud_tf/x:
      min: -0.25
      max: 0.25
      is_repeat: false
  - /point_cloud_tf/y:
      min: -0.25
      max: 0.25
      is_repeat: false
  - /point_cloud_tf/z:
      min: -0.25
      max: 0.25
      is_repeat: false
  - /point_cloud_tf/roll:
      min: -10.0
      max: 10.0
      is_repeat: false
  - /point_cloud_tf/pitch:
      min: -10.0
      max: 10.0
      is_repeat: false
  - /point_cloud_tf/yaw:
      min: -10.0
      max: 10.0
      is_repeat: false
  - /point_cloud_tf/save_data:
      is_repeat: false
